# Default NBA API parameters for traditional player stats
TRADITIONAL_PARAMS = {
    "Season": "2025-26",
    "SeasonType": "Regular Season",
    "PerMode": "PerGame",
    "PlayerExperience": "",
    "PlayerPosition": "",
    "College": "",
    "Country": "",
    "DraftPick": "",
    "DraftYear": "",
    "GameScope": "",
    "GameSegment": "",
    "Height": "",
    "Month": "0",
    "OpponentTeamID": "0",
    "Outcome": "",
    "PORound": "0",
    "Period": "0",
    "ShotClockRange": "",
    "TeamID": "0",
    "VsConference": "",
    "VsDivision": "",
    "Weight": ""
}
