"""Add teams and schedule_games tables

Revision ID: 000e230c3235
Revises: 59476cf1fb3b
Create Date: 2026-01-21 19:07:49.590026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000e230c3235'
down_revision: Union[str, Sequence[str], None] = '59476cf1fb3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('abbreviation', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation', name='uq_team_abbr')
    )
    op.create_table('game_schedule',
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('season_type', sa.Text(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_abbr', sa.Text(), nullable=True),
    sa.Column('away_team_abbr', sa.Text(), nullable=True),
    sa.Column('matchup', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('game_id', name='uq_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_schedule')
    op.drop_table('teams')
    # ### end Alembic commands ###
