"""add player and player_game_stats tables

Revision ID: 0a4108fb9071
Revises: f09ee2200f19
Create Date: 2026-01-17 15:28:57.877556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4108fb9071'
down_revision: Union[str, Sequence[str], None] = 'f09ee2200f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('team_abbreviation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('rebounds', sa.Float(), nullable=True),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    op.drop_table('players')
    # ### end Alembic commands ###
