"""Add teams and schedule_games tables

Revision ID: 59476cf1fb3b
Revises: 0a4108fb9071
Create Date: 2026-01-21 19:01:33.739067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59476cf1fb3b'
down_revision: Union[str, Sequence[str], None] = '0a4108fb9071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
