"""add lineup_stats

Revision ID: 8c1065ec23b5
Revises: 8ed1ac5bd62a
Create Date: 2026-01-27 14:56:50.407725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1065ec23b5'
down_revision: Union[str, Sequence[str], None] = '8ed1ac5bd62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Text(), nullable=True),
    sa.Column('lineup_id', sa.Text(), nullable=True),
    sa.Column('lineup', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('ast_pct', sa.Float(), nullable=True),
    sa.Column('reb_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'lineup_id', name='uq_lineup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup_stats')
    # ### end Alembic commands ###
