"""add team_game_stats

Revision ID: 8ed1ac5bd62a
Revises: 000e230c3235
Create Date: 2026-01-27 14:32:45.877956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed1ac5bd62a'
down_revision: Union[str, Sequence[str], None] = '000e230c3235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_abbreviation', sa.Text(), nullable=True),
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('rebounds', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'game_id', name='uq_team_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game_stats')
    # ### end Alembic commands ###
