"""initial odds schema

Revision ID: f09ee2200f19
Revises: 
Create Date: 2026-01-15 22:16:35.890193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09ee2200f19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('sport_key', sa.Text(), nullable=False),
    sa.Column('sport_title', sa.Text(), nullable=False),
    sa.Column('commence_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('home_team', sa.Text(), nullable=False),
    sa.Column('away_team', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_props')
    op.drop_table('markets')
    op.drop_table('bookmakers')
    op.drop_table('events')
    # ### end Alembic commands ###
